// data.js

// --- ASCENDANCIES ---
const ASCENDANCIES = {
    standard: [
        { name: "Juggernaut", class: "Marauder" },
        { name: "Berserker", class: "Marauder" },
        { name: "Chieftain", class: "Marauder" },
        { name: "Slayer", class: "Duelist" },
        { name: "Gladiator", class: "Duelist" },
        { name: "Champion", class: "Duelist" },
        { name: "Deadeye", class: "Ranger" },
        { name: "Raider", class: "Ranger" },
        { name: "Pathfinder", class: "Ranger" },
        { name: "Assassin", class: "Shadow" },
        { name: "Saboteur", class: "Shadow" },
        { name: "Trickster", class: "Shadow" },
        { name: "Necromancer", class: "Witch" },
        { name: "Occultist", class: "Witch" },
        { name: "Elementalist", class: "Witch" },
        { name: "Inquisitor", class: "Templar" },
        { name: "Hierophant", class: "Templar" },
        { name: "Guardian", class: "Templar" },
        { name: "Ascendant", class: "Scion" }
    ],
    // Based on the Legacy of Phrecia Event (3.25 Event)
    phrecia: [
        { name: "Antiquarian", class: "Marauder" },
        { name: "Behemoth", class: "Marauder" },
        { name: "Ancestral Commander", class: "Marauder" },
        { name: "Gambler", class: "Duelist" },
        { name: "Paladin", class: "Duelist" },
        { name: "Aristocrat", class: "Duelist" },
        { name: "Daughter of Oshabi", class: "Ranger" },
        { name: "Whisperer", class: "Ranger" },
        { name: "Wildspeaker", class: "Ranger" },
        { name: "Surfcaster", class: "Shadow" },
        { name: "Servant of Arakaali", class: "Shadow" },
        { name: "Blind Prophet", class: "Shadow" },
        { name: "Harbinger", class: "Witch" },
        { name: "Herald", class: "Witch" },
        { name: "Bog Shaman", class: "Witch" },
        { name: "Polytheist", class: "Templar" },
        { name: "Scavenger", class: "Scion" } // Often associated with the "Wildcard" replacement
    ]
};

// --- KEYSTONES ---
// Uses exact Wiki names for image fetching
const KEYSTONES = [
    "Acrobatics", "Ancestral Bond", "Arrow Dancing", "Avatar of Fire",
    "Blood Magic", "Chaos Inoculation", "Crimson Dance", "Divine Shield",
    "Eldritch Battery", "Elemental Overload", "Ghost Reaver", "Glancing Blows",
    "Hollow Palm Technique", "Imbalanced Guard", "Iron Grip", "Iron Reflexes",
    "Iron Will", "Lethe Shade", "Magebane", "Mind Over Matter",
    "Minion Instability", "Oath of the Maji", "Pain Attunement", "Perfect Agony",
    "Point Blank", "Precise Technique", "Resolute Technique", "Runebinder",
    "Solipsism", "Supreme Ego", "The Agnostic", "The Impaler",
    "Unwavering Stance", "Vaal Pact", "Wicked Ward", "Wind Dancer",
    "Zealot's Oath"
];

// --- SKILL GEMS ---
// This list excludes supports/auras to ensure "Main Skill" viability.
// Format: "Base Skill": ["Transfig 1", "Transfig 2"]
const SKILLS_DB = {
    "Absolution": ["of Inspiring"],
    "Arc": ["of Oscillating", "of Surging"],
    "Artillery Ballista": ["of Crossfire", "of Focus"],
    "Ball Lightning": ["of Orbiting", "of Static"],
    "Bane": ["of Condemnation"],
    "Barrage": ["of Volley Fire"],
    "Blade Blast": ["of Dagger Detonation", "of Unloading"],
    "Blade Flurry": ["of Incision"],
    "Blade Trap": ["of Greatswords", "of Laceration"],
    "Blade Vortex": ["of the Scythe"],
    "Bladefall": ["of Impaling", "of Volleys"],
    "Bladestorm": ["of Uncertainty"],
    "Blast Rain": [],
    "Blazing Salvo": [],
    "Blight": ["of Atrophy", "of Contagion"],
    "Blink Arrow": ["of Bombarding Clones", "of Prismatic Clones"],
    "Body Swap": [],
    "BoneShatter": ["of Carnage", "of Complex Trauma"],
    "Burning Arrow": ["of Vigour"],
    "Caustic Arrow": ["of Poison"],
    "Chain Hook": [],
    "Charged Dash": [],
    "Cleave": ["of Rage"],
    "Cobra Lash": [],
    "Cold Snap": ["of Power"],
    "Consecrated Path": ["of Endurance"],
    "Contagion": ["of Subsiding", "of Transference"],
    "Crackling Lance": ["of Branching", "of Disintegration"],
    "Creeping Frost": [],
    "Cremation": ["of Exhuming", "of the Volcano"],
    "Cyclone": ["of Tumult"],
    "Dark Pact": [],
    "Desecrate": [],
    "Detonate Dead": ["of Chain Reaction", "of Scavenging"],
    "Discharge": ["of Misery"],
    "Divine Ire": ["of Disintegration", "of Holy Lightning"],
    "Dominating Blow": ["of Inspiring"],
    "Double Strike": ["of Impaling", "of Momentum"],
    "Dual Strike": ["of Ambidexterity"],
    "Earthquake": ["of Amplification"],
    "Earthshatter": [],
    "Elemental Hit": ["of the Spectrum"],
    "Energy Blade": [],
    "Essence Drain": ["of Desperation", "of Wickedness"],
    "Ethereal Knives": ["of the Massacre", "of Lingering Blades"],
    "Explosive Arrow": [],
    "Explosive Concoction": ["of Destruction"],
    "Explosive Trap": ["of Magnitude", "of Shrapnel"],
    "Exsanguinate": ["of Transmission"],
    "Eye of Winter": ["of Finality", "of Transience"],
    "Fire Trap": ["of Blasting"],
    "Fireball": ["of Dragon's Breath"],
    "Firestorm": ["of Meteors", "of Pelting"],
    "Flame Dash": ["of Return"], // Can be main skill if you are brave
    "Flame Surge": ["of Combusting"],
    "Flame Wall": [],
    "Flameblast": ["of Celerity", "of Contraction"],
    "Flicker Strike": ["of Power"],
    "Forbidden Rite": ["of Soul Sacrifice"],
    "Freezing Pulse": [],
    "Frenzy": ["of Onslaught"],
    "Frost Blades": ["of Katabasis"],
    "Frost Bomb": ["of Forthcoming", "of Instability"],
    "Frost Wall": [],
    "Frostblink": ["of Wintry Blast"],
    "Frozen Legion": ["of Rallying"],
    "Galvanic Arrow": ["of Energy", "of Surging"],
    "Galvanic Field": ["of Intensity"],
    "General's Cry": [],
    "Glacial Cascade": ["of the Fissure"],
    "Glacial Hammer": ["of Shattering"],
    "Ground Slam": ["of Earthshaking"],
    "Heavy Strike": [],
    "Herald of Agony": [], // Minion build
    "Herald of Purity": [], // Minion build
    "Herald of Thunder": [], // Autobomber
    "Hexblast": ["of Contradiction", "of Havoc"],
    "Holy Flame Totem": ["of Ire"],
    "Ice Crash": ["of Cadence"],
    "Ice Nova": ["of Deep Freeze", "of Frostbolts"],
    "Ice Shot": ["of Penetration"],
    "Ice Spear": ["of Splitting"],
    "Ice Trap": ["of Hollowness"],
    "Icicle Mine": ["of Fanning", "of Sabotage"],
    "Incinerate": ["of Expanse", "of Venting"],
    "Infernal Blow": ["of Immolation"],
    "Kinetic Blast": ["of Clustering"],
    "Kinetic Bolt": ["of Fragmentation"],
    "Lacerate": ["of Butchering", "of Haemorrhage"],
    "Lancing Steel": ["of Spraying"],
    "Leap Slam": ["of Groundbreaking"],
    "Lightning Arrow": ["of Electrocution"],
    "Lightning Conduit": ["of the Heavens"],
    "Lightning Spire Trap": ["of Overloading", "of Zapping"],
    "Lightning Strike": ["of Arcing"],
    "Lightning Tendrils": ["of Eccentricity", "of Escalation"],
    "Lightning Trap": ["of Sparking"],
    "Lightning Warp": [],
    "Magma Orb": [], // Rolling Magma
    "Manabond": [],
    "Mirror Arrow": ["of Bombarding Clones", "of Prismatic Clones"],
    "Molten Shell": [], // Armor stacker main skill?
    "Molten Strike": ["of the Zenith"],
    "Orb of Storms": [],
    "Penance Brand": ["of Conduction", "of Dissipation"],
    "Perforate": ["of Bloodshed", "of Duality"],
    "Pestilent Strike": [],
    "Power Siphon": ["of the Archmage"],
    "Puncture": [],
    "Purifying Flame": ["of Revelations"],
    "Pyroclast Mine": ["of Sabotage"],
    "Rage Vortex": ["of Berserking"],
    "Rain of Arrows": ["of Artillery", "of Saturation"],
    "Raise Spectre": ["of Transience"],
    "Raise Zombie": ["of Falling", "of Slamming"],
    "Reap": [],
    "Reave": ["of Refraction"],
    "Reckoning": [],
    "Righteous Fire": ["of Arcane Devotion"],
    "Riposte": [],
    "Rolling Magma": ["of Ruin"],
    "Scorching Ray": ["of Immolation"],
    "Scourge Arrow": ["of Menace"],
    "Searing Bond": [],
    "Seismic Trap": ["of Swells"],
    "Shattering Steel": ["of Ammunition"],
    "Shield Charge": [],
    "Shield Crush": ["of the Chieftain"],
    "Shock Nova": [],
    "Shockwave Totem": [],
    "Shrapnel Ballista": ["of Steel"],
    "Siege Ballista": ["of Splintering"],
    "Smite": ["of Divine Judgement"],
    "Soulrend": ["of Reaping", "of the Spiral"],
    "Spark": ["of the Nova", "of Unpredictability"],
    "Spectral Helix": [],
    "Spectral Shield Throw": ["of Shattering"],
    "Spectral Throw": ["of Materialising"],
    "Split Arrow": ["of Splitting"],
    "Splitting Steel": ["of Ammunition"],
    "Static Strike": [],
    "Storm Brand": ["of Indecision"],
    "Storm Burst": [],
    "Storm Call": [],
    "Storm Rain": ["of the Conduit", "of the Fence"],
    "Stormbind": ["of Teleportation"],
    "Summon Carrion Golem": ["of Hordes", "of Scavenging"],
    "Summon Chaos Golem": ["of Hordes", "of the Maelstrom"],
    "Summon Flame Golem": ["of Hordes", "of the Meteor"],
    "Summon Holy Relic": ["of Conviction"],
    "Summon Ice Golem": ["of Hordes", "of Shattering"],
    "Summon Lightning Golem": ["of Hordes"],
    "Summon Raging Spirit": ["of Enormity"],
    "Summon Reaper": ["of Eviscerating", "of Revenants"],
    "Summon Skeletons": ["of Archers", "of Mages"],
    "Summon Stone Golem": ["of Hordes", "of Safeguarding"],
    "Sunder": ["of Earthbreaking"],
    "Sweep": [],
    "Tectonic Slam": ["of Cataclysm"],
    "Tempest Shield": [],
    "Tornado Shot": [],
    "Toxic Rain": ["of Sporeburst", "of Withering"],
    "Unearth": [],
    "Vengeance": [],
    "Venom Gyre": [],
    "Viper Strike": ["of the Mamba"],
    "Void Sphere": ["of Rending"],
    "Volatile Dead": ["of Confinement", "of Seething"],
    "Volcanic Fissure": ["of Snaking"],
    "Vortex": ["of Projection"],
    "Wave of Conviction": [],
    "Wild Strike": ["of Extremes"],
    "Winter Orb": [],
    "Wintertide Brand": []
};